### ISSUE TITLE
mcpets reload bug

### ISSUE THREAD

**Issue by LuluxClient** [Nocsy-Workshop/mcpets#15]
Some language entries won't change even after a restart and a /mcpets reload for example: **rename_item_description** won't change even if you edit the text, Some other entries requires a full restart just to edit the menu title and many more. https://gyazo.com/c017ba82ff69bf225d6c71b0ae964e84

**Comment by AlexandreChaussard** [comment]
Parts of the language is cached, so it needs server restart.
