### ISSUE TITLE
MCPets laggs while opening a menu

### ISSUE THREAD

**Issue by Tomut0** [Nocsy-Workshop/mcpets#18]
It seems, MCPets doesn't use cache system when working with database. 
Therefore, we got a huge lag here.

https://spark.lucko.me/xLtPhoZWxa

**Comment by AlexandreChaussard** [comment]
It should be using a cache system. Can you point out where in the code it doesn't use cache for DB plz ?

**Comment by Tomut0** [comment]
Kinda outdated, at a first glance codebase looks much better now.
Closed.
