### ISSUE TITLE
Is there any consideration for Vulcan anti-cheat compatibility?

### ISSUE THREAD

**Issue by NEIKI19914** [Nocsy-Workshop/mcpets#29]
![UJA__SC 9WW0$}@`IKGI2W](https://github.com/Nocsy-Workshop/mcpets/assets/59737752/6de94304-bdfb-4108-98ea-c754ee384743)
![TJV@%GZLU90D9NY_R72H)}U](https://github.com/Nocsy-Workshop/mcpets/assets/59737752/c726e98e-5022-4601-8374-07e0e61de3ef)
![BM{ZSYC2%TP)T4Y8PRW{U01](https://github.com/Nocsy-Workshop/mcpets/assets/59737752/a5b060c5-d75f-4037-8069-bfd6dde2a5ff)
Same as the title.... Vulcan anti-cheat seems to have a misjudgment on MCpet... And ItemsAdder also has some plugins that are already compatible with Vulcan Anti-Cheat.

**Comment by AlexandreChaussard** [comment]
It's not MCPets that handles the mounting, but ModelEngine. You'll need to report the issue to them directly.
