### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by robtbs** [Nocsy-Workshop/mcpets#30]
5.11 21:35:40 [Server] ERROR Error occurred (in the plugin loader) while disabling MCPets v4.1.1 (Is it up to date?)
25.11 21:35:40 [Server] INFO java.lang.NoClassDefFoundError: com/ticxo/modelengine/api/mount/controller/MountControllerSupplier
25.11 21:35:40 [Server] INFO at fr.nocsy.mcpets.MCPets.onDisable(MCPets.java:111) ~[MCPets_4.1.1-MEG4.jar:?]
25.11 21:35:40 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
25.11 21:35:40 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[paper-1.20.1.jar:git-Paper-196]
25.11 21:35:40 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[paper-1.20.1.jar:git-Paper-196]
25.11 21:35:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
25.11 21:35:40 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[paper-1.20.1.jar:git-Paper-196]
25.11 21:35:40 [Server] INFO at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-196]
25.11 21:35:40 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
25.11 21:35:40 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:642) ~[paper-1.20.1.jar:git-Paper-196]
25.11 21:35:40 [Server] INFO at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:553) ~[paper-1.20.1.jar:git-Paper-196]
25.11 21:35:40 [Server] INFO at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:635) ~[paper-1.20.1.jar:git-Paper-196]
25.11 21:35:40 [Server] INFO at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:434) ~[paper-1.20.1.jar:git-Paper-196]
25.11 21:35:40 [Server] INFO at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-196]
25.11 21:35:40 [Server] INFO at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1100) ~[paper-1.20.1.jar:git-Paper-196]
25.11 21:35:40 [Server] INFO at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:317) ~[paper-1.20.1.jar:git-Paper-196]
25.11 21:35:40 [Server] INFO at java.lang.Thread.run(Thread.java:840) ~[?:?]
25.11 21:35:40 [Server] INFO Caused by: java.lang.ClassNotFoundException: com.ticxo.modelengine.api.mount.controller.MountControllerSupplier
25.11 21:35:40 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:183) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
25.11 21:35:40 [Server] INFO at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:150) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
25.11 21:35:40 [Server] INFO at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
25.11 21:35:40 [Server] INFO ... 16 more

**Comment by AlexandreChaussard** [comment]
Check the plugins requirements:
https://mcpets.gitbook.io/mcpets/common-issues/common-issues/requirements
