### ISSUE TITLE
Pet wont fly in MEG4 version

### ISSUE THREAD

**Issue by LPPRR123** [Nocsy-Workshop/mcpets#33]
my pet wont fly, I pressed space button but it just jumping.

using
paperspigot 1.20.4
ModelEngine-4.0.6.1
MCPets_4.1.3-MEG4 
Mythicmob 5.6.2

this issue occurred after i update meg3 to meg4

pet config: https://pastebin.com/tXikjC0s
mm skill config: https://pastebin.com/sL1NzBPP
mm mob config: https://pastebin.com/2exqhq4s

**Comment by AlexandreChaussard** [comment]
Hi! Maybe the Pet Config does not use the `flying` option for mounts? It can also be an issue with ModelEngine if everything is setup correctly.
